### ISSUE TITLE
Allowing certain Headers

### ISSUE THREAD

**Issue by RyanW8** [haproxytech/haproxy-lua-cors#16]
I'm getting the following error:

`Request header field x-scope-orgid is not allowed by Access-Control-Allow-Headers in preflight response.`

with this configuration in my frontend

```
    http-request set-header Access-Control-Allow-Headers "X-Scope-OrgID, Content-Type, Authorization"
    http-response set-header Access-Control-Allow-Headers "X-Scope-OrgID, Content-Type, Authorization"
    acl cortex_ruler_acl ssl_fc_sni cortex-ruler.n4monitoring.co.uk
    acl cortex_distributor_acl ssl_fc_sni cortex-distributor.n4monitoring.co.uk
    acl cortex_frontend_acl ssl_fc_sni cortex.n4monitoring.co.uk
    # Capture Origin request header
    http-request lua.cors "*" "*" if cortex_ruler_acl OR cortex_distributor_acl OR cortex_frontend_acl
    http-response lua.cors if cortex_ruler_acl OR cortex_distributor_acl OR cortex_frontend_acl
```

Any idea?

**Comment by NickMRamirez** [comment]
If you are using HAProxy 2.2 or newer, this Lua module will return a response to a preflight request without forwarding the request to the backend server. This is an improvement because it means the backend server doesn't have to deal with OPTIONS requests. However, since the Lua code sends the response itself, any `http-response set-header` lines will not be invoked.

The module needs another line in the `preflight_request_ver2` method:

```
reply:add_header("Access-Control-Allow-Headers", "X-Custom-Id")
```

But, it should probably have a way for someone to pass the headers in from the haproxy.cfg, and also a default value if no headers are passed. It should be an easy update, which I should have time for tomorrow or the day after.

**Comment by RyanW8** [comment]
Yeah thats the workaround which I ended up doing, editing the lua file directly. Although having the ability to pass headers through  using the haproxy.cfg would be ideal.

**Comment by RyanW8** [comment]
Any update on this @NickMRamirez

**Comment by NickMRamirez** [comment]
Fixed this in the latest commit.
