### ISSUE TITLE
origin:match

### ISSUE THREAD

**Issue by RealUrsus** [haproxytech/haproxy-lua-cors#21]
Could you please clarify the logic behind:  elseif contains(allowed_origins, origin:match("//([^/]+)")) then
while it gives a permanent error for the allowed endpoint (book.***.com):

Jan 21 13:53:52 lb11 haproxy[13613]: CORS: Got 'Origin' header: book.***.com
Jan 21 13:53:52 lb11 haproxy[13613]: [debug] 020/135352 (13613) : CORS: Got 'Origin' header: book.***.com
Jan 21 13:53:52 lb11 haproxy[13613]: CORS: book.***.com not allowed
Jan 21 13:53:52 lb11 haproxy[13613]: [debug] 020/135352 (13613) : CORS: book.***.com not allowed

a simple script is confirming: 
origin = "api.test.com"
as = origin:match("//([^/]+)")
print(as)

output: nil

**Comment by RealUrsus** [comment]
Sorry, forgot to mention:
    elseif contains(allowed_origins, origin) then

is working as expected...

**Comment by NickMRamirez** [comment]
The Lua `string.match` function matches a string against a pattern. Since our pattern uses a capture group, only the part of the string captured is returned.

Example:

```lua
local str = "https://www.example.com"
local out = str:match("//([^/]+)")
print(out) --prints www.example.com
```
Test here: https://glot.io/new/lua

So, the `string.match` function normalizes the origin before sending it to the `contains` function. We are stripping off the scheme (e.g. http:// or https://) from the URL. The `contains` function checks whether the normalized origin exists in the "allowed_origins" table.

An Origin HTTP header should always have a scheme. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

If your origin does not have a scheme, then it will not match. Does your origin have a scheme? If not, why?

**Comment by RealUrsus** [comment]
You right, I was missed the scheme part from my picture completely...
Thank you very much for clarification!
